apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: federation-external-secret
spec:
  refreshInterval: 1h
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Federation
          name: local-federation-generator
