apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "federation.fullname" . }}
  namespace: {{ include "federation.namespace" . }}
  labels:
    {{- include "federation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "federation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "federation.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "federation.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- if .Values.controller.priorityClassName }}
      priorityClassName: {{ .Values.controller.priorityClassName }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: federation
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --metrics-addr=:{{ .Values.metrics.port }}
            - --health-probe-bind-address=:{{ .Values.probe.port }}
            - --controller-class={{ .Values.controller.class }}
            - --concurrent={{ .Values.controller.concurrent }}
            - --client-qps={{ .Values.controller.clientQPS }}
            - --client-burst={{ .Values.controller.clientBurst }}
            - --server-port=:{{ .Values.service.port }}
            - --server-tls-port=:{{ .Values.service.tlsPort }}
            - --enable-federation-tls={{ .Values.service.enableTLS }}
            - --spire-agent-socket-path={{ .Values.controller.spireAgentSocketPath }}
            - --enable-flood-gate={{ .Values.controller.floodGate }}
            - --enable-http2={{ .Values.controller.enableHTTP2 }}
            - --zap-time-encoding={{ .Values.controller.log.timeEncoding }}
            - --loglevel={{ .Values.controller.log.level }}
            {{- if .Values.controller.leaderElection }}
            - --leader-elect=true
            {{- end }}
            {{- if .Values.metrics.secure.enabled }}
            - --metrics-secure=true
            - --metrics-cert-dir={{ .Values.metrics.secure.certDir }}
            - --metrics-cert-name={{ .Values.metrics.secure.certFile }}
            - --metrics-key-name={{ .Values.metrics.secure.keyFile }}
            {{- end }}
            {{- range $arg := .Values.controller.extraArgs }}
            - {{ $arg | quote }}
            {{- end }}
          env:
            {{- with .Values.controller.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.controller.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: server
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.service.enableTLS }}
            - name: server-tls
              containerPort: {{ .Values.service.tlsPort }}
              protocol: TCP
            {{- end }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          {{- if and .Values.probe.liveness.enabled .Values.probe.liveness.path }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.path }}
              port: {{ .Values.probe.port }}
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
          {{- end }}
          {{- if and .Values.probe.readiness.enabled .Values.probe.readiness.path }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.path }}
              port: {{ .Values.probe.port }}
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.controller.extraVolumeMounts .Values.metrics.secure.enabled }}
          volumeMounts:
            {{- if .Values.metrics.secure.enabled }}
            - name: metrics-tls
              mountPath: {{ .Values.metrics.secure.certDir }}
              readOnly: true
            {{- end }}
            {{- with .Values.controller.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      hostNetwork: {{ .Values.controller.hostNetwork }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.controller.extraVolumes .Values.metrics.secure.enabled }}
      volumes:
        {{- if .Values.metrics.secure.enabled }}
        - name: metrics-tls
          secret:
            secretName: {{ default (printf "%s-metrics-tls" (include "federation.fullname" .)) .Values.metrics.secure.secretName }}
        {{- end }}
        {{- with .Values.controller.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
