apiVersion: v1
kind: Service
metadata:
  name: {{ include "federation.fullname" . }}-server
  namespace: {{ include "federation.namespace" . }}
  labels:
    {{- include "federation.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml .Values.service.ipFamilies | nindent 4 }}
  {{- end }}
  selector:
    {{- include "federation.selectorLabels" . | nindent 4 }}
  ports:
    - name: server
      port: {{ .Values.service.port }}
      targetPort: server
      protocol: TCP
    {{- if .Values.service.enableTLS }}
    - name: server-tls
      port: {{ .Values.service.tlsPort }}
      targetPort: server-tls
      protocol: TCP
    {{- end }}
