{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "federation.fullname" . }}
  namespace: {{ include "federation.namespace" . }}
  labels:
    {{- include "federation.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "federation.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scheme: {{ ternary "https" "http" .Values.metrics.secure.enabled }}
{{- end }}
