apiVersion: generators.external-secrets.io/v1alpha1
kind: Fake
metadata:
  name: federation-generator
  namespace: federation-example
spec:
  data:
    username: "test-user"
    password: "test-password"
    api-key: "1234567890abcdef"
