apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-federation-generator
  namespace: federation-example
spec:
  refreshInterval: 1h
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Fake
          name: federation-generator
